---
- name: "1. Type: Bug"
  color: D93F0B
  description: "Inconsistencies or issues which will cause a problem for users."

- name: "1. Type: Crash"
  color: FF5733
  description: "Critical errors causing the modpack to crash."

- name: "1. Type: Question"
  color: d876e3
  description: "Further information is requested."

- name: "1. Type: Feature"
  color: 542D50
  description: "New feature or request."

- name: "1. Type: Duplicate"
  color: cfd3d7
  description: "This issue or pull request already exists."

- name: "1. Type: Invalid"
  color: e4e669
  description: "This doesn't seem right."

- name: "1. Type: Other Issue"
  color: 1BEAFC
  description: "Miscellaneous issues not covered by other labels."



- name: "2. Status: Accepted"
  color: 1F973A
  description: "Feature accepted."

- name: "2. Status: Cannot reproduce"
  color: A45D0F
  description: "We can't reproduce the issue."

- name: "2. Status: Confirmed"
  color: 83F727
  description: "Bug confirmed."

- name: "2. Status: Help wanted"
  color: A84740
  description: "Extra attention is needed."

- name: "2. Status: In Dev"
  color: 4F38A2
  description: "Currently in development."

- name: "2. Status: Unverified"
  color: 36C8A2
  description: "Bug unverified."

- name: "2. Status: Wontfix"
  color: ffffff
  description: "This will not be worked on."

- name: "2. Status: Not a TFG Bug"
  color: E938DF
  description: "Not our issue."



- name: "3. Priority: Critical"
  color: ee0701
  description: "Must be addressed as soon as possible."

- name: "3. Priority: High"
  color: B60205
  description: "Issue or PR should be prioritized for reviews."

- name: "3. Priority: Medium"
  color: 0E8A16
  description: "Important but not urgent."

- name: "3. Priority: Low"
  color: 1D76DB
  description: "Low priority."

- name: "3. Priority: Long-term plans"
  color: BFD4F2
  description: "Planned for future implementation."


- name: "1. PR: Dependencies"
  color: 0366d6
  description: "Pull requests that update a dependency file."

- name: "4. PR: Translation"
  color: 4C6DD0
  description: "The pull request concerns translation."

- name: "4. PR: Documentation"
  color: 007BFF
  description: "Pull request includes documentation updates."

- name: "4. PR: Experimental"
  color: FD7E14
  description: "Pull request includes experimental features or changes."

- name: "4. PR: Feature"
  color: E83E8C
  description: "Pull request adds a new feature."

- name: "4. PR: Hotfix"
  color: E83E8C
  description: "Pull request addresses an urgent issue that needs immediate attention."

- name: "4. PR: Deprecated"
  color: 808080
  description: "Pull request deprecates existing functionality."
