name: "[RU] Запросить функцию"
description: Запросите новую функцию или изменение существующей.
labels: [ "1. Type: Feature" ]
body:
  - type: input
    id: version
    attributes:
      label: Версия модпака.
      description: Напишите, какую версию модпака вы используете.
      placeholder: "Пример: 0.1.1"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Связанная проблема
      description: Если функция, которую вы хотите изменить, связана с проблемой, опишите ее. Оставьте это поле пустым, если оно не связано с проблемой.
      placeholder: "Пример: Я всегда расстраиваюсь, когда..."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Ваше решение
      description: Опишите решение, которое вы хотели бы получить.
      placeholder: "Пример: Если бы я мог..."
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Дополнительная информация
      description: Любая дополнительная информация, которую вы хотите предоставить. Пожалуйста, добавьте сюда все, что не вошло в другие разделы.
      placeholder: "Пример: Это, вероятно, достижимо, выполнив X, потому что..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: Спасибо, что нашли время, чтобы заполнить этот запрос функции.
