name: "[RU] Отчет об ошибке"
description: Сообщите об ошибке, когда что-то работает не так, как ожидалось, что не приводит к сбою игры.
labels: [ "1. Type: Bug", "2. Status: Unverified" ]
body:
  - type: input
    id: version
    attributes:
      label: Версия модпака.
      description: Напишите, какую версию модпака вы используете.
      placeholder: "Пример: 0.1.1"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Среда запуска
      description: "Как вы играли в мире. Типичные ответы: одиночная игра, игра по локальной сети, сервер Forge, сервер Sponge или сервер Mohist"
      placeholder: "Пример: одиночная игра"
    validations:
      required: true
  - type: dropdown
    id: world
    attributes:
      label: Новые миры
      description: Этот сбой происходит во вновь созданном мире?
      options:
        - "Да"
        - "Нет"
        - "Не уверен"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
      description: То, что вы ожидали, произойдет. При необходимости прикрепите сюда скриншоты.
      placeholder: "Пример: ожидается производство X при потреблении Y."
    validations:
      required: true
  - type: textarea
    id: result
    attributes:
      label: Фактическое поведение
      description: Что произошло вопреки вашим ожиданиям. При необходимости прикрепите сюда скриншоты.
      placeholder: "Пример: произведено одно изделие X, но Y не было потреблено."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Действия по воспроизведению
      description: Как воспроизвести сбой.
      placeholder: "Пример: 1) я сделал X…"
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Дополнительная информация
      description: Любая дополнительная информация, которую вы хотите предоставить. Пожалуйста, добавьте сюда все, что не вошло в другие разделы.
      placeholder: "Пример: это, вероятно, вызвано Х, потому что…"
    validations:
      required: false
  - type: markdown
    attributes:
      value: Спасибо, что нашли время заполнить этот отчет об ошибке.
