name: Project Release
run-name: "Project Release #${{ github.run_number }}"

on:
  workflow_call:
    inputs:
      project_version:
        required: true
        type: string
      project_name:
        required: true
        type: string
      project_full_name:
        required: true
        type: string
      changelog:
        required: true
        type: string
      truncated_changelog:
        required: true
        type: string
      diff:
        required: true
        type: string
      release_type:
        required: true
        type: string
      minecraft_version:
        required: true
        type: string

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-curseforge:
    name: Release to CurseForge
    runs-on: ubuntu-latest
    outputs:
      id: ${{ steps.release.outputs.id }}
    steps:
      - name: Check if CURSEFORGE_TOKEN exist
        shell: bash
        run: |
          if [ "${{ secrets.CURSEFORGE_TOKEN }}" == '' ]; then
            echo '::error::No value found for secret key `CURSEFORGE_TOKEN`. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
          fi  

      - name: Download artifact curseforge
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ needs.info.outputs.project_full_name }}-curseforge

      - name: Download artifact server
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ needs.info.outputs.project_full_name }}-serverpack

      - name: Upload Curseforge
        id: release
        uses: Xikaro/upload-curseforge-modpack-action@1.1.1
        with:
          api-token: ${{ secrets.CURSEFORGE_TOKEN }}
          project-id: ${{ vars.CURSEFORGE_ID }}
          display-name: ${{ needs.info.outputs.project_full_name }}
          modpack-path: ${{ needs.info.outputs.project_full_name }}-curseforge.zip
          server-display-name: ${{ needs.info.outputs.project_full_name }}-serverpack
          modpack-server-path: ${{ needs.info.outputs.project_full_name }}-serverpack.zip
          changelog: |
            ${{ needs.info.outputs.changelog }}
            ${{ needs.info.outputs.diff }}
          changelog-format: markdown
          game-version: ${{ needs.info.outputs.minecraft_version }}
          release-type: ${{ needs.info.outputs.release_type }}

  release-modrinth:
      name: Release to Modrinth
      runs-on: ubuntu-latest
      steps:
        - name: Check if MODRINTH_API_TOKEN exist
          shell: bash
          run: |
            if [ "${{ secrets.MODRINTH_TOKEN }}" == '' ]; then
              echo '::error::No value found for secret key `MODRINTH_TOKEN`. See https://docs.github.com/en/  actionssecurity-guides/  encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
            fi  
    
        - name: Download artifact modrinth
          uses: actions/download-artifact@v4.1.8
          with:
            name: ${{ needs.info.outputs.project_full_name }}-modrinth
    
        - name: Download artifact server
          uses: actions/download-artifact@v4.1.8
          with:
            name: ${{ needs.info.outputs.project_full_name }}-serverpack
    
        - name: Upload Modrinth
          id: release
          uses: Xikaro/upload-curseforge-modpack-action@1.1.1
          with:
            api-token: ${{ secrets.MODRINTH_TOKEN }}
            project-id: ${{ vars.MODRINTH_ID }}
            modpack-path: ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack
            modpack-server-path: ${{ needs.info.outputs.project_full_name }}-serverpack.zip
            changelog: ${{ needs.info.outputs.changelog }}
            changelog-format: markdown
            game-version: ${{ needs.info.outputs.minecraft_version }}
            display-name: ${{ needs.info.outputs.project_full_name }}
            server-display-name: ${{ needs.info.outputs.project_full_name }}-serverpack
            release-type: ${{ needs.info.outputs.release_type }}

  release-github:
    name: Release to GitHub
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.release.outputs.url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          merge-multiple: true

      - name: Сlose fixed in dev
        uses: Xikaro/close-issues-based-on-label@master
        env:
          LABEL: "2. Status: In Dev"
          COMMENT: In ${{ needs.info.outputs.project_version }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: release
        uses: softprops/action-gh-release@v2.0.9
        with:
          name: ${{ needs.info.outputs.project_version }}
          tag_name: ${{ needs.info.outputs.project_version }}
          body: |
            ${{ needs.info.outputs.changelog }}
            ```markdown
            ${{ needs.info.outputs.diff }}
            ```
          files: |
            ${{ needs.info.outputs.project_full_name }}-curseforge.zip
            ${{ needs.info.outputs.project_full_name }}-serverpack.zip
            ${{ needs.info.outputs.project_full_name }}-multimc.zip
          prerelease: ${{ env.RELEASE_TYPE != 'release' }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

  discord-message:
    name: Discord Message
    needs: [release-curseforge, release-github]
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord message
        uses: hugoalh/send-discord-webhook-ghaction@v7.0.2
        with:
          key: ${{ secrets.DISCORD_RELEASES }}
          username: "TerraFirmaGreg"
          avatar_url: "https://raw.githubusercontent.com/TerraFirmaGreg-Team/.github/main/branding/logo.png"
          content_links_no_embed: .+
          content: |
            **Release**: `${{ needs.info.outputs.project_version }}`
            **Release Type**: `${{ needs.info.outputs.release_type }}`
            **Game Version**: `${{ needs.info.outputs.minecraft_version }}`

            [CurseForge](https://www.curseforge.com/minecraft/modpacks/terrafirmagreg-vintage/files/${{ needs.release-curseforge.outputs.id }}) • [GitHub](${{ needs.release-github.outputs.url }}) • [Issues](https://github.com/${{ github.repository }}/issues)

             ```markdown
            ${{ needs.info.outputs.truncated_changelog }}
            - ...```
            ** [Read more...](${{ needs.release-github.outputs.url }}) **
